### ISSUE TITLE
trouble with npm install in starting-from-webapp and in javascript-app

### ISSUE THREAD

**Issue by Joffin21** [screencloud/developer#165]
I've tried to follow along with the documentation but as soon as I reach the npm install (which is one of the first steps said in the readme for the starting-from-webapp or javascript-app folders), I am left with numerous errors. It seems like npm install isn't properly producing the node_modules folder, or if it does, then it gets rid of it at the end with a build error. 

[Log](https://drive.google.com/file/d/1C5sCzf1mSzApiRZHDivr11Age_uwj1gw/view?usp=sharing)

That should be a link to the full log I get when trying to run npm install.

**Comment by lbaldrickSC** [comment]
https://github.com/screencloud/developer/commit/4a08dc6d3861617e2dbb2077eaea75f8ef3de1ff fixed with is commit
